create extension if not exists pgcrypto with schema extensions;

create table if not exists public.client_delivery_projects (
  id uuid primary key default gen_random_uuid(),
  access_code_digest text not null unique,
  code_hint text not null,
  client_display_name text not null,
  project_name text not null,
  brand text not null check (brand in ('OWNYOURWEB', 'SHOPNASGFX', 'OWNYOURWEB + SHOPNASGFX')),
  status text not null default 'ready' check (status in ('preparing', 'ready', 'archived')),
  status_label text not null default 'Files ready',
  delivery_note text not null default 'Your approved files are available below.',
  source_project_slug text,
  is_active boolean not null default true,
  expires_at timestamptz,
  last_accessed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_delivery_files (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.client_delivery_projects(id) on delete cascade,
  storage_path text not null unique,
  display_name text not null,
  folder text not null default 'Project files',
  description text,
  mime_type text not null,
  extension text,
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_delivery_access_log (
  id bigint generated by default as identity primary key,
  project_id uuid references public.client_delivery_projects(id) on delete set null,
  code_fingerprint text not null,
  ip_fingerprint text not null,
  success boolean not null,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists client_delivery_files_project_sort_idx
  on public.client_delivery_files(project_id, sort_order, created_at);

create index if not exists client_delivery_access_log_ip_time_idx
  on public.client_delivery_access_log(ip_fingerprint, created_at desc);

create index if not exists client_delivery_access_log_project_idx
  on public.client_delivery_access_log(project_id);

alter table public.client_delivery_projects enable row level security;
alter table public.client_delivery_files enable row level security;
alter table public.client_delivery_access_log enable row level security;

drop policy if exists "client delivery projects private" on public.client_delivery_projects;
create policy "client delivery projects private"
  on public.client_delivery_projects for all to public
  using (false) with check (false);

drop policy if exists "client delivery files private" on public.client_delivery_files;
create policy "client delivery files private"
  on public.client_delivery_files for all to public
  using (false) with check (false);

drop policy if exists "client delivery access log private" on public.client_delivery_access_log;
create policy "client delivery access log private"
  on public.client_delivery_access_log for all to public
  using (false) with check (false);

revoke all on public.client_delivery_projects from anon, authenticated;
revoke all on public.client_delivery_files from anon, authenticated;
revoke all on public.client_delivery_access_log from anon, authenticated;

grant select, update on public.client_delivery_projects to service_role;
grant select on public.client_delivery_files to service_role;
grant select, insert on public.client_delivery_access_log to service_role;
grant usage, select on sequence public.client_delivery_access_log_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'client-deliveries',
  'client-deliveries',
  false,
  262144000,
  array[
    'application/pdf',
    'application/postscript',
    'application/zip',
    'application/x-zip-compressed',
    'application/octet-stream',
    'application/vnd.adobe.photoshop',
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/svg+xml',
    'video/mp4',
    'video/quicktime',
    'video/webm',
    'audio/mpeg',
    'audio/wav'
  ]::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.client_delivery_projects is 'Private code-gated delivery spaces for OWNYOURWEB and SHOPNASGFX clients.';
comment on column public.client_delivery_projects.access_code_digest is 'Lowercase SHA-256 digest of a high-entropy client code. Never store the raw code.';
